spring:
  # 排除自动配置 - 这是关键！
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
  cloud:
    gateway:
      gateway-token: bKAgyPdf0jz9UvNAD1NwQwQc1ewWzreXHK732quM5UY=
    nacos:
      username: cloud_developer
      password: 745700Yxy@
      config:
        server-addr: 127.0.0.1:8848
        namespace: cloud_${spring.profiles.active}
        file-extension: yaml
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
  config:
    import:
      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}

# 这些配置不够强，需要配合上面的 autoconfigure.exclude
management:
  metrics:
    enable:
      process.cpu: false
      system.cpu: false
      jvm.memory.max: false
      jvm.memory.used: false