spring:
  cloud:
    nacos:
      username: cloud_developer
      password: 745700Yxy@
      config:
        server-addr: 127.0.0.1:8848
        namespace: cloud_${spring.profiles.active}
        file-extension: yaml
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
  config:
    import:
      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}